- hosts: localhost
  gather_facts: False
  tasks:
  - include_vars: ../config/cem.config

  - name: Get AWS info
    amazon.aws.aws_caller_info:
    register: caller_info

  - name: Delete users
    community.aws.iam_user:
      name: "{{ item }}"
      state: absent
    loop:
      - Robert
      - Mike
      - John
      - "{{ AWS_YOURSELF }}"

  - name: Delete groups
    community.aws.iam_group:
      name: "{{ item }}"
      state: absent
    loop:
      - Admins
      - Developers 

  - name: Delete SAML Provider
    community.aws.iam_saml_federation:
      name: "{{ AWS_SAML_PROVIDER_NAME }}"
      state: absent
      
  - name: Delete S3 Bucket
    amazon.aws.s3_bucket:
      name: "{{ AWS_S3_BUCKET_NAME }}"
      state: absent
      force: yes
    when:  not AWS_SKIP_S3_WHEN_CLEANUP

  - name: Purge policies from AWS-IDP-AdminAccess-Role
    community.aws.iam_role:
      name: AWS-IDP-AdminAccess-Role
      assume_role_policy_document: 
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRoleWithSAML
          Effect: Allow
          Principal:
            Federated: "arn:aws:iam::{{ caller_info.account }}:saml-provider/{{ AWS_SAML_PROVIDER_NAME }}"  
          Condition:
            StringEquals:
              "SAML:aud": "https://signin.aws.amazon.com/saml"
      purge_policies: true
      managed_policies: []

  - name: Purge policies from AWS_ServiceRole_EC2FullAccess
    community.aws.iam_role:
      name: AWS_ServiceRole_EC2FullAccess
      assume_role_policy_document: 
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
      purge_policies: true
      managed_policies: []

  - name: Delete roles
    community.aws.iam_role:
      name: "{{ item }}"
      state: absent
    loop:
      - AWS-IDP-AdminAccess-Role
      - AWS_ServiceRole_EC2FullAccess

  - name: Delete S3 bucket policy
    community.aws.iam_managed_policy:
      policy_name: "S3_BucketAccess_Policy"
      state: absent